-- ============================================================
--  VadeMed · Configuración de Supabase
--  Ejecuta TODO este archivo una sola vez en:
--  Supabase → SQL Editor → New query → pega esto → Run
-- ============================================================

-- 1) Tabla de PERFILES (un renglón por usuario, con sus datos y su sync)
create table if not exists public.perfiles (
  id uuid primary key references auth.users on delete cascade,
  email text,
  nombre text,
  rol text,
  especialidad text,
  genero text,
  favoritos jsonb default '[]'::jsonb,
  quiz jsonb default '{}'::jsonb,
  updated_at timestamptz default now()
);

alter table public.perfiles enable row level security;

drop policy if exists "ver_propio"    on public.perfiles;
drop policy if exists "crear_propio"  on public.perfiles;
drop policy if exists "editar_propio" on public.perfiles;

create policy "ver_propio"    on public.perfiles for select using (auth.uid() = id);
create policy "crear_propio"  on public.perfiles for insert with check (auth.uid() = id);
create policy "editar_propio" on public.perfiles for update using (auth.uid() = id);

-- 2) Tabla de SUGERENCIAS (cualquiera puede enviar; solo tú las lees desde el panel)
create table if not exists public.sugerencias (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users on delete set null,
  email text,
  texto text not null,
  app text,
  created_at timestamptz default now()
);

alter table public.sugerencias enable row level security;

drop policy if exists "enviar_sugerencia" on public.sugerencias;

-- Permite INSERTAR sugerencias (usuarios con o sin sesión).
create policy "enviar_sugerencia" on public.sugerencias for insert with check (true);

-- Nota: no hay policy de SELECT para el público, así que NADIE puede LEER las
-- sugerencias desde la app; tú las ves en Supabase → Table editor → sugerencias.
